# -*- coding: utf-8 -*-
"""Genty_Eva_2_Application_032026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yi7WWnnmPBaP_8NVvdvkwpG1ZNtHDaK8
"""

import pandas as pd
import joblib

def check_billets(fichier_csv):
    model = joblib.load('/content/Model_Final.pkl')
    scaler = joblib.load('/content/Scaler.pkl')
    colonnes = ['diagonal', 'height_left', 'height_right', 'margin_low', 'margin_up', 'length']


    if isinstance(fichier_csv, str):
        df = pd.read_csv(fichier_csv, sep=None, engine='python')
    else:
        df = pd.DataFrame([fichier_csv], columns=colonnes)

    #Au cas ou fichier avec nulls
    df = df.dropna(subset=colonnes)

    #Scaler sur fichier
    fichier_scaler = scaler.transform(df[colonnes])

    df['Résultats avec notre modèle'] = ['VRAI' if p == 1 else 'FAUX' for p in model.predict(fichier_scaler)]

    #Modele sur fichier
    probas = model.predict_proba(fichier_scaler)
    df['Probabilité que le billet soit vrai'] = [f"{p[1]*100:.2f}%" for p in probas]

#facilités d'affichage
    colonnes_affichage = ['id', 'Résultats avec notre modèle', 'Probabilité que le billet soit vrai']

    #Securisation si manque une colonne
    actuelles_colonnes = [c for c in colonnes_affichage if c in df.columns]

    print(df[actuelles_colonnes])


#Resultats sur le fichier de test
#Cas saisie manuelle pour check d'une ligne peut être pratique
#expertise_billets([171.45, 104.21, 104.18, 4.55, 3.52, 113.21])

#Cas csv plus simple si plusieurs billets avec des numéros de billets
check_billets('test2.csv')


#Fichier à télécharger en .py pour une utilisation externe => avec nom de fichier en imput à changer